/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.*;
import javax.swing.*;
import logicaJuego.LogicaJuego;

/**
 *
 * @author balyg
 */
public class Juego extends javax.swing.JFrame {

    private Vfondo fondo;
    private LogicaJuego log = new LogicaJuego();
    private boolean caraUp = false;
    private ImageIcon im1;
    private ImageIcon im2;
    private JButton[] btnP = new JButton[2];
    private boolean primerc = false;
    private int puntaje = 0;

    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
        fondo = new Vfondo(getWidth(), getHeight());
        add(fondo, BorderLayout.CENTER);
        aleatorio();
    }

    private void aleatorio() {
        int[] number = log.getCardNumbers();
        C1.setDisabledIcon(new ImageIcon(getClass().getResource("../img/carta" + number[0] + ".jpg")));
        C2.setDisabledIcon(new ImageIcon(getClass().getResource("../img/carta" + number[1] + ".jpg")));
        C3.setDisabledIcon(new ImageIcon(getClass().getResource("../img/carta" + number[2] + ".jpg")));
        C4.setDisabledIcon(new ImageIcon(getClass().getResource("../img/carta" + number[3] + ".jpg")));
        C5.setDisabledIcon(new ImageIcon(getClass().getResource("../img/carta" + number[4] + ".jpg")));
        C6.setDisabledIcon(new ImageIcon(getClass().getResource("../img/carta" + number[5] + ".jpg")));
        C7.setDisabledIcon(new ImageIcon(getClass().getResource("../img/carta" + number[6] + ".jpg")));
        C8.setDisabledIcon(new ImageIcon(getClass().getResource("../img/carta" + number[7] + ".jpg")));
        C9.setDisabledIcon(new ImageIcon(getClass().getResource("../img/carta" + number[8] + ".jpg")));
        C10.setDisabledIcon(new ImageIcon(getClass().getResource("../img/carta" + number[9] + ".jpg")));
        C11.setDisabledIcon(new ImageIcon(getClass().getResource("../img/carta" + number[10] + ".jpg")));
        C12.setDisabledIcon(new ImageIcon(getClass().getResource("../img/carta" + number[11] + ".jpg")));
        C13.setDisabledIcon(new ImageIcon(getClass().getResource("../img/carta" + number[12] + ".jpg")));
        C14.setDisabledIcon(new ImageIcon(getClass().getResource("../img/carta" + number[13] + ".jpg")));
        C15.setDisabledIcon(new ImageIcon(getClass().getResource("../img/carta" + number[14] + ".jpg")));
        C16.setDisabledIcon(new ImageIcon(getClass().getResource("../img/carta" + number[15] + ".jpg")));

    }

    private void btnEnable(JButton btn) {

        if (!caraUp) {
            btn.setEnabled(false);
            im1 = (ImageIcon) btn.getDisabledIcon();
            btnP[0] = btn;
            caraUp = true;
            primerc = false;
        } else {
            btn.setEnabled(false);
            im2=(ImageIcon) btn.getDisabledSelectedIcon();
            btnP[1] = btn;
            primerc = true;
            puntaje += 100;
            ganador();
        };

    }

    private void compare() {
        if (caraUp && primerc) {
            if (im1.getDescription().compareTo(im2.getDescription()) != 0){
                btnP[0].setEnabled(true);
                btnP[1].setEnabled(true);
                if (puntaje > 50) puntaje -=50;
            }
            caraUp = false;
        }  
    }
    
    private void reiniciar()
    {
        aleatorio();
        C1.setEnabled(true);
        C2.setEnabled(true);
        C3.setEnabled(true);
        C4.setEnabled(true);
        C5.setEnabled(true);
        C6.setEnabled(true);
        C7.setEnabled(true);
        C8.setEnabled(true);
        C9.setEnabled(true);
        C10.setEnabled(true);
        C11.setEnabled(true);
        C12.setEnabled(true);
        C13.setEnabled(true);
        C14.setEnabled(true);
        C15.setEnabled(true);
        C16.setEnabled(true);
        
        primerc = false;
        caraUp = false;
        puntaje = 0;
        aleatorio();
    }

    private  void ganador(){
        if (!C1.isEnabled() && !C2.isEnabled() && !C3.isEnabled() && !C4.isEnabled() && 
            !C5.isEnabled() && !C6.isEnabled() && !C7.isEnabled() && !C8.isEnabled() && 
            !C9.isEnabled() && !C10.isEnabled() &&!C11.isEnabled() && !C12.isEnabled() && 
            !C13.isEnabled() && !C14.isEnabled() && !C15.isEnabled() && !C16.isEnabled() ) 
        {
            JOptionPane.showMessageDialog(this,"Felicidades, usted ha ganado\nSu puntaje es:"+puntaje ,"WIN",JOptionPane.INFORMATION_MESSAGE);
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        C1 = new javax.swing.JButton();
        C2 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        C5 = new javax.swing.JButton();
        C6 = new javax.swing.JButton();
        C7 = new javax.swing.JButton();
        C8 = new javax.swing.JButton();
        C9 = new javax.swing.JButton();
        C10 = new javax.swing.JButton();
        C11 = new javax.swing.JButton();
        C12 = new javax.swing.JButton();
        C13 = new javax.swing.JButton();
        C14 = new javax.swing.JButton();
        C15 = new javax.swing.JButton();
        C16 = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego 2 Cartas");

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel1.setText("             BIENVENIDOS");

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentMoved(evt);
            }
        });

        C1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.jpg"))); // NOI18N
        C1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        C1.setContentAreaFilled(false);
        C1.setFocusable(false);
        C1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.jpg"))); // NOI18N
        C1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                C1MouseExited(evt);
            }
        });
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });

        C2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.jpg"))); // NOI18N
        C2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        C2.setContentAreaFilled(false);
        C2.setFocusable(false);
        C2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.jpg"))); // NOI18N
        C2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                C2MouseExited(evt);
            }
        });
        C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2ActionPerformed(evt);
            }
        });

        C3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.jpg"))); // NOI18N
        C3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        C3.setContentAreaFilled(false);
        C3.setFocusable(false);
        C3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.jpg"))); // NOI18N
        C3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                C3MouseExited(evt);
            }
        });
        C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3ActionPerformed(evt);
            }
        });

        C4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.jpg"))); // NOI18N
        C4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        C4.setContentAreaFilled(false);
        C4.setFocusable(false);
        C4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.jpg"))); // NOI18N
        C4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                C4MouseExited(evt);
            }
        });
        C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C4ActionPerformed(evt);
            }
        });

        C5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.jpg"))); // NOI18N
        C5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        C5.setContentAreaFilled(false);
        C5.setFocusable(false);
        C5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.jpg"))); // NOI18N
        C5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                C5MouseExited(evt);
            }
        });
        C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C5ActionPerformed(evt);
            }
        });

        C6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.jpg"))); // NOI18N
        C6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        C6.setContentAreaFilled(false);
        C6.setFocusable(false);
        C6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.jpg"))); // NOI18N
        C6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                C6MouseExited(evt);
            }
        });
        C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C6ActionPerformed(evt);
            }
        });

        C7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.jpg"))); // NOI18N
        C7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        C7.setContentAreaFilled(false);
        C7.setFocusable(false);
        C7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.jpg"))); // NOI18N
        C7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                C7MouseExited(evt);
            }
        });
        C7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C7ActionPerformed(evt);
            }
        });

        C8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.jpg"))); // NOI18N
        C8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        C8.setContentAreaFilled(false);
        C8.setFocusable(false);
        C8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.jpg"))); // NOI18N
        C8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                C8MouseExited(evt);
            }
        });
        C8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C8ActionPerformed(evt);
            }
        });

        C9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.jpg"))); // NOI18N
        C9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        C9.setContentAreaFilled(false);
        C9.setFocusable(false);
        C9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.jpg"))); // NOI18N
        C9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                C9MouseExited(evt);
            }
        });
        C9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C9ActionPerformed(evt);
            }
        });

        C10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.jpg"))); // NOI18N
        C10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        C10.setContentAreaFilled(false);
        C10.setFocusable(false);
        C10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.jpg"))); // NOI18N
        C10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                C10MouseExited(evt);
            }
        });
        C10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C10ActionPerformed(evt);
            }
        });

        C11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.jpg"))); // NOI18N
        C11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        C11.setContentAreaFilled(false);
        C11.setFocusable(false);
        C11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.jpg"))); // NOI18N
        C11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                C11MouseExited(evt);
            }
        });
        C11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C11ActionPerformed(evt);
            }
        });

        C12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.jpg"))); // NOI18N
        C12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        C12.setContentAreaFilled(false);
        C12.setFocusable(false);
        C12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.jpg"))); // NOI18N
        C12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                C12MouseExited(evt);
            }
        });
        C12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C12ActionPerformed(evt);
            }
        });

        C13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.jpg"))); // NOI18N
        C13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        C13.setContentAreaFilled(false);
        C13.setFocusable(false);
        C13.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.jpg"))); // NOI18N
        C13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                C13MouseExited(evt);
            }
        });
        C13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C13ActionPerformed(evt);
            }
        });

        C14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.jpg"))); // NOI18N
        C14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        C14.setContentAreaFilled(false);
        C14.setFocusable(false);
        C14.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.jpg"))); // NOI18N
        C14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                C14MouseExited(evt);
            }
        });
        C14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C14ActionPerformed(evt);
            }
        });

        C15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.jpg"))); // NOI18N
        C15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        C15.setContentAreaFilled(false);
        C15.setFocusable(false);
        C15.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.jpg"))); // NOI18N
        C15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                C15MouseExited(evt);
            }
        });
        C15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C15ActionPerformed(evt);
            }
        });

        C16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.jpg"))); // NOI18N
        C16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        C16.setContentAreaFilled(false);
        C16.setFocusable(false);
        C16.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.jpg"))); // NOI18N
        C16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                C16MouseExited(evt);
            }
        });
        C16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(C9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(C13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(C16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(C1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(C5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(C6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(C2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(C4)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(C1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(C2)
                    .addComponent(C3)
                    .addComponent(C4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(C6)
                    .addComponent(C5)
                    .addComponent(C7)
                    .addComponent(C8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(C10)
                    .addComponent(C9)
                    .addComponent(C11)
                    .addComponent(C12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(C13)
                    .addComponent(C14)
                    .addComponent(C15)
                    .addComponent(C16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(319, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnReiniciar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel1ComponentMoved

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
        // TODO add your handling code here:
        btnEnable(C1);
    }//GEN-LAST:event_C1ActionPerformed

    private void C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2ActionPerformed
        // TODO add your handling code here:
        btnEnable(C2);
    }//GEN-LAST:event_C2ActionPerformed

    private void C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3ActionPerformed
        btnEnable(C3);
    }//GEN-LAST:event_C3ActionPerformed

    private void C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C4ActionPerformed
        btnEnable(C4);
    }//GEN-LAST:event_C4ActionPerformed

    private void C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C5ActionPerformed
        btnEnable(C5);
    }//GEN-LAST:event_C5ActionPerformed

    private void C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C6ActionPerformed
        btnEnable(C6);
    }//GEN-LAST:event_C6ActionPerformed

    private void C7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C7ActionPerformed
        btnEnable(C7);
    }//GEN-LAST:event_C7ActionPerformed

    private void C8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C8ActionPerformed
        btnEnable(C8);
    }//GEN-LAST:event_C8ActionPerformed

    private void C9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C9ActionPerformed
        btnEnable(C9);
    }//GEN-LAST:event_C9ActionPerformed

    private void C10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C10ActionPerformed
        btnEnable(C10);
    }//GEN-LAST:event_C10ActionPerformed

    private void C11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C11ActionPerformed
        btnEnable(C11);
    }//GEN-LAST:event_C11ActionPerformed

    private void C12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C12ActionPerformed
        btnEnable(C12);
    }//GEN-LAST:event_C12ActionPerformed

    private void C13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C13ActionPerformed
        btnEnable(C13);
    }//GEN-LAST:event_C13ActionPerformed

    private void C14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C14ActionPerformed
        btnEnable(C14);
    }//GEN-LAST:event_C14ActionPerformed

    private void C15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C15ActionPerformed
        btnEnable(C15);
    }//GEN-LAST:event_C15ActionPerformed

    private void C16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C16ActionPerformed
        btnEnable(C16);
    }//GEN-LAST:event_C16ActionPerformed

    private void C1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C1MouseExited
        // TODO add your handling code here:
        compare();
    }//GEN-LAST:event_C1MouseExited

    private void C2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C2MouseExited
        // TODO add your handling code here:
        compare();
    }//GEN-LAST:event_C2MouseExited

    private void C3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C3MouseExited
        // TODO add your handling code here:
        compare();
    }//GEN-LAST:event_C3MouseExited

    private void C4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C4MouseExited
        // TODO add your handling code here:
        compare();
    }//GEN-LAST:event_C4MouseExited

    private void C5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C5MouseExited
        // TODO add your handling code here:
        compare();
    }//GEN-LAST:event_C5MouseExited

    private void C6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C6MouseExited
        // TODO add your handling code here:
        compare();
    }//GEN-LAST:event_C6MouseExited

    private void C7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C7MouseExited
        // TODO add your handling code here:
        compare();
    }//GEN-LAST:event_C7MouseExited

    private void C8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C8MouseExited
        // TODO add your handling code here:
        compare();
    }//GEN-LAST:event_C8MouseExited

    private void C9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C9MouseExited
        // TODO add your handling code here:
        compare();
    }//GEN-LAST:event_C9MouseExited

    private void C10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C10MouseExited
        // TODO add your handling code here:
        compare();
    }//GEN-LAST:event_C10MouseExited

    private void C11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C11MouseExited
        // TODO add your handling code here:
        compare();
    }//GEN-LAST:event_C11MouseExited

    private void C12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C12MouseExited
        // TODO add your handling code here:
        compare();
    }//GEN-LAST:event_C12MouseExited

    private void C13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C13MouseExited
        // TODO add your handling code here:
        compare();
    }//GEN-LAST:event_C13MouseExited

    private void C14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C14MouseExited
        // TODO add your handling code here:
        compare();
    }//GEN-LAST:event_C14MouseExited

    private void C15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C15MouseExited
        // TODO add your handling code here:
        compare();
    }//GEN-LAST:event_C15MouseExited

    private void C16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C16MouseExited
        // TODO add your handling code here:
        compare();
    }//GEN-LAST:event_C16MouseExited

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        // TODO add your handling code here:
        reiniciar();
    }//GEN-LAST:event_btnReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton C1;
    private javax.swing.JButton C10;
    private javax.swing.JButton C11;
    private javax.swing.JButton C12;
    private javax.swing.JButton C13;
    private javax.swing.JButton C14;
    private javax.swing.JButton C15;
    private javax.swing.JButton C16;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton C4;
    private javax.swing.JButton C5;
    private javax.swing.JButton C6;
    private javax.swing.JButton C7;
    private javax.swing.JButton C8;
    private javax.swing.JButton C9;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
